apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-claims-api.fullname" . }}
  labels:
    {{- include "data-claims-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      {{- include "data-claims-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-claims-api.selectorLabels" . | nindent 8 }}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
    spec:
      serviceAccountName: "{{ .Values.service_account.name }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ "ALL" ]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AUTHORIZED_CLIENTS
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: authorized-clients
            - name: AUTHORIZED_ROLES
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: authorized-roles
            - name: UNPROTECTED_URIS
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: unprotected-uris
            - name: QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: sqs-queue-name
            - name: SNS_TOPIC_ARN
              valueFrom:
                secretKeyRef:
                  name: claims-events-sns-topic
                  key: topic_arn
            - name: REPORTING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: reporting-username
            - name: REPORTING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: reporting-password
            - name: DATA_FACTORY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: data-factory-username
            - name: DATA_FACTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: data-factory-password
            {{ include "dbConnectionDetails" . | nindent 12 }}
            - name: DB_URL
              value: "jdbc:postgresql://$(DB_HOST):5432/$(DB_NAME)"
            - name: HIKARI_MIN_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: hikari-minimum-pool-size
            - name: HIKARI_MAX_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: hikari-maximum-pool-size
            - name: HIKARI_IDLE_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: hikari-idle-timeout
            - name: CLAIMS_API_AMENDMENTS_ENABLED
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: amendments-enabled
                  optional: true
            - name: HIKARI_CONNECTION_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: hikari-connection-timeout
            - name: PROVIDER_DETAILS_API_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: provider-details-api-access-token
            - name: PROVIDER_DETAILS_API_URL
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: provider-details-api-url
            - name: FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: fee-scheme-platform-api-access-token
            - name: FEE_SCHEME_PLATFORM_API_URL
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: fee-scheme-platform-api-url
            - name: FEE_SCHEME_PLATFORM_API_READ_TIMEOUT_MS
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: fee-scheme-platform-api-read-timeout-ms
                  optional: true
            - name: FEE_SCHEME_PLATFORM_API_CONNECT_TIMEOUT_MS
              valueFrom:
                secretKeyRef:
                  name: laa-data-claims-api-secrets
                  key: fee-scheme-platform-api-connect-timeout-ms
                  optional: true
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profile | quote }}
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            {{ include "sentryConfig" . | nindent 12 }}
